# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on macOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  QT5_DIR: "/usr/local/opt/qt@5/lib/cmake/Qt5"
  OpenMP_ROOT: "/usr/local/Cellar/libomp/18.1.8"

jobs:
  build:
    # https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job#standard-github-hosted-runners-for-public-repositories
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.MUSICARDIOTOKEN }}
        submodules: true

    - name: Install dependencies
      run: |
        # brew info cmake
        brew install qt@5
        brew install boost
        # brew info swig
        # brew info libomp        
        pip3 install dmgbuild

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DQt5_DIR=${{env.QT5_DIR}} -DOpenMP_ROOT=${{env.OpenMP_ROOT}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    # - name: Push to private repository
    #   run: |
    #     git clone https://github.com/username/private-repo.git
    #     cd private-repo
    #     cp ../build/path/to/your/binary .
    #     git add .
    #     git commit -m "Add new binary"
    #     git push https://${{ secrets.MYTOKEN }}@github.com/username/private-repo.git
