# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: medInria on macOS

on:
  push:
    branches: [ "testCImed" ]
  workflow_dispatch:
    inputs:
      BRANCH:
        description: 'Branch to checkout'
        required: false
        default: 'testCImed'
        type: string
  workflow_call:
    inputs:
      BRANCH:
        required: false
        type: string
        default: 'testCImed'
      RELEASE:
        required: false
        type: string
        default: 'V4.0.2'

env:
  BUILD_TYPE: Release
  #QT5_DIR: "/opt/homebrew/opt/qt@5/lib/cmake/Qt5" # Apple chip
  QT5_DIR: "/usr/local/opt/qt@5/lib/cmake/Qt5" # Intel chip

  # Token added on https://github.com/Inria-Asclepios/medInria-public/settings/secrets/actions/new and on your fork for testing purpose
  # MSC_SSH_PLUGINS: ${{ secrets.MSC_SSH_PLUGINS }}
  # MSC_TOKEN: ${{ secrets.MSC_TOKEN }}
  BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
  P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
  CERT_NAME: "MDS-certificate"

jobs:
  build:
    # https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job#standard-github-hosted-runners-for-public-repositories
    # See documentation for our selfhosted runners https://github.com/Inria-Asclepios/music/wiki/Github-Action
    runs-on: macos-26-intel #macos-latest (Apple chip)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
      with:
          ref: ${{ inputs.BRANCH }}

    - name: Install dependencies
      run: |
        brew install qt@5
        #echo 'export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"' >> /Users/runner/.bash_profile # Apple chip
        echo 'export PATH="/usr/local/opt/qt@5/bin:$PATH"' >> /Users/runner/.bash_profile # Intel chip
        brew link --force qt@5
        sudo ln -s /usr/local/Cellar/qt@5/5.15.18/mkspecs /usr/local/mkspecs
        sudo ln -s /usr/local/Cellar/qt@5/5.15.18/plugins /usr/local/plugins
        brew install boost
        brew install swig
        brew install libomp
        echo "OpenMP_ROOT=$(brew --prefix libomp)" >> $GITHUB_ENV

        # to get an older version of CMake
        brew uninstall --ignore-dependencies cmake
        pipx install cmake==3.31.10

    - name: Test dependencies
      run: |
        cmake --version
        ls $QT5_DIR

    ### Steps for macOS signing with self-signed certificate ###
    #
    # 1. Create a p12 certificate on a physical macOS https://github.com/Inria-Asclepios/music/wiki/Binaries-signature.
    # 2. On the mac, copy the p12 certificate with: 'base64 -i MDS-certificate.p12 | pbcopy'.
    # 3. On https://github.com/medInria/medInria-public/settings/secrets/actions/new
    #   - add BUILD_CERTIFICATE_BASE64 with the previously encoded lines,
    #   - add P12_PASSWORD with p12 password.
    # 4. For test purposes you need to add the secrets also on your fork.
    ###

    # https://github.com/marketplace/actions/import-code-signing-certificates
    - name: Install our self-signed certificate
      id: import-certs
      uses: apple-actions/import-codesign-certs@v7
      with: 
        p12-file-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        p12-password:    ${{ secrets.P12_PASSWORD }}

    - name: Add the certificate to trusted list for code signing
      shell: bash
      run: |
        # Extract the PEM certificate from the p12
        echo "$BUILD_CERTIFICATE_BASE64" | base64 --decode > /tmp/cert.p12
        openssl pkcs12 -legacy -in /tmp/cert.p12 -passin pass:"$P12_PASSWORD" -clcerts -nokeys -out /tmp/cert.pem

        # Add trusted certificate to system keychain
        sudo security add-trusted-cert -d -r trustRoot -p codeSign \
          -k /Library/Keychains/System.keychain /tmp/cert.pem

    - name: Add keychain from import-codesign-certs step to search list
      shell: bash
      run: |
        security list-keychains -d user -s \
          "$HOME/Library/Keychains/signing_temp.keychain-db" \
          "$HOME/Library/Keychains/login.keychain-db" \
          /Library/Keychains/System.keychain

    - name: Verify certificate
      shell: bash
      run: |
        # List every identities
        security find-identity -v -p codesigning

        # Search for our certificate
        security find-identity -v -p codesigning | grep -F -q "$CERT_NAME" || {
          echo "Error, certificate '$CERT_NAME' not found in valid identities"
          exit 1
        }

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
          -DUSE_GITHUB_SSH:BOOL=FALSE \
          -DmedInria_BUILD_TYPE:STRING=${{env.BUILD_TYPE}} \
          -DEP_CHECKBOX_CUSTOM_DIRS:BOOL=ON \
          -DEP_CHECKBOX_ON_TOP_LEVEL:BOOL=OFF \
          -DEP_CHECKBOX_SIDE_BY_SIDE:BOOL=OFF \
          -DQt5_DIR=$QT5_DIR \
          -DOpenMP_ROOT=$OpenMP_ROOT

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel 4

    - name: Package
      run: |
        # security find-identity -v -p codesigning
        # security find-identity -v -p codesigning ~/Library/Keychains/login.keychain-db

        cd ${{github.workspace}}/build
        cpack -C ${{env.BUILD_TYPE}}

    - name: Get binary name
      run: |
        cd ${{github.workspace}}/build
        binary=$(ls *.dmg | head -n 1)
        echo "BINARY_NAME=$binary" >> $GITHUB_ENV
        echo "The current package: $binary"
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: ${{github.workspace}}/build/${{env.BINARY_NAME}}
        asset_name: ${{env.BINARY_NAME}}
        tag: ${{ inputs.RELEASE }}
        overwrite: true
