# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: MUSICardio on macOS

on:
  push:
    branches: [ "dev" ]
  # pull_request:
  #   branches: [ "dev" ]
  workflow_dispatch:
    inputs:
      EXPIRATION_TIME:
        description: 'Expiration time in month'
        required: true
        default: '24'
        type: string
  #schedule:
  #  - cron: '0 0 * * 1'  # Each monday at 0h00, MIN HOUR DAY_IN_MONTH MONTH WEEK_DAY

env:
  BUILD_TYPE: Release
  QT5_DIR: "/opt/homebrew/opt/qt@5/lib/cmake/Qt5"
  MSC_SSH_PLUGINS: ${{ secrets.MSC_SSH_PLUGINS }}
  MSC_TOKEN: ${{ secrets.MSC_TOKEN }}

jobs:
  build:
    # https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job#standard-github-hosted-runners-for-public-repositories
    runs-on: macos-15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          ref: dev

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "$MSC_SSH_PLUGINS" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Install dependencies
      run: |
        brew install qt@5
        echo 'export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"' >> /Users/runner/.bash_profile
        brew link --force qt@5
        sudo ln -s /usr/local/Cellar/qt@5/5.15.18/mkspecs /usr/local/mkspecs
        sudo ln -s /usr/local/Cellar/qt@5/5.15.18/plugins /usr/local/plugins
        brew install boost
        brew install swig
        brew install libomp
        echo "OpenMP_ROOT=$(brew --prefix libomp)" >> $GITHUB_ENV
        #brew install pipx
        pipx install dmgbuild
        pipx ensurepath
        #brew info cmake
        brew uninstall --ignore-dependencies cmake
        pipx install cmake==3.31.10

    - name: Test dependencies
      run: |
        pipx --version
        which dmgbuild
        cmake --version
        ls $QT5_DIR

    - name: Set default EXPIRATION_TIME if not provided (with non manual workflow)
      run: echo "EXPIRATION_TIME=${{ inputs.EXPIRATION_TIME || '24' }}" >> $GITHUB_ENV

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
          -DUSE_GITHUB_SSH:BOOL=TRUE \
          -DmedInria_BUILD_TYPE:STRING=$BUILD_TYPE \
          -Dmusic-plugins_BUILD_TYPE:STRING=$BUILD_TYPE \
          -DEP_CHECKBOX_CUSTOM_DIRS:BOOL=ON \
          -DEP_CHECKBOX_ON_TOP_LEVEL:BOOL=OFF \
          -DEP_CHECKBOX_SIDE_BY_SIDE:BOOL=OFF \
          -DQt5_DIR=$QT5_DIR \
          -DOpenMP_ROOT=$OpenMP_ROOT \
          -DEXPIRATION_TIME:STRING=$EXPIRATION_TIME \
          -DUSE_RealTimeWorkspace=OFF
          
    - name: Build
      run: | 
        CORES_TO_USE=$(($(sysctl -n hw.ncpu) - 1)) # Limit the number of used core otherwise the compilation crashes sometimes
        echo "Using $CORES_TO_USE cores for the build"
        cmake --build ${{github.workspace}}/build --config $BUILD_TYPE --parallel $CORES_TO_USE

    - name: Package
      run: |
        cd ${{github.workspace}}/build
        cpack -C $BUILD_TYPE

    - name: Get DMG name
      run: |
        cd ${{github.workspace}}/build
        dmg=$(ls *.dmg | head -n 1)
        echo "DMG_NAME=$dmg" >> $GITHUB_ENV
        echo "The current package: $dmg"
      
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_name: Inria-Asclepios/msc_binaries
        # A personal access token for the GitHub repository in which the release will be created and edited.
        # It is recommended to create the access token with the following scopes: `repo, user, admin:repo_hook`.
        repo_token: ${{ secrets.MSC_TOKEN }}
        file: ${{github.workspace}}/build/${{env.DMG_NAME}}
        asset_name: ${{env.DMG_NAME}}
        tag: latest
        overwrite: true
        body: "MUSICardio binaries"
